# Generated by Django 4.2.23 on 2025-08-09 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selectable_params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=datetime.date.today, verbose_name='Дата выполнения')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('comment', models.TextField(max_length=300, null=True, verbose_name='Комментарий')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selectable_params.categories', verbose_name='Категория')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selectable_params.statuses', verbose_name='Статус')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selectable_params.subcategories', verbose_name='Подкатегория')),
                ('type_operation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selectable_params.types_operations', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Движение денежных средств',
                'verbose_name_plural': 'Движения денежных средств',
                'db_table': 'cash_flow',
                'ordering': ('date_creation',),
            },
        ),
    ]
