# Generated by Django 4.2.23 on 2025-08-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash_flow',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cash_flow',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='cash_flow',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='cash_flow',
            old_name='type_operation_id',
            new_name='type_operation',
        ),
    ]
