version: '3'

services:
  web:
    build: .
    # context: .
    # dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/django-app
    command: python /django-app/manage.py runserver 0.0.0.0:8000
