# Generated by Django 4.2.23 on 2025-08-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectable_params', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='type_operation_id',
            new_name='type_operation',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
